#!/bin/sh
set -ve
./handaxeweb.lua handaxeweb.lua 0 < handaxeweb.haw > handaxeweb2.lua

# test new version
lua handaxeweb2.lua handaxeweb.lua 0 < handaxeweb.haw > handaxeweb3.lua

# try building it with itself:
lua handaxeweb3.lua handaxeweb.lua 0 < handaxeweb.haw > handaxeweb4.lua

# verify output is the same:
diff handaxeweb3.lua handaxeweb4.lua

# okay, we’ll accept it
cp handaxeweb4.lua handaxeweb.lua

./handaxeweb.lua build_handaxeweb 0 < handaxeweb.haw > build_handaxeweb.new
cp build_handaxeweb.new build_handaxeweb
